[package]
name = "kommand0-tui"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tokio.workspace = true
futures.workspace = true
nix.workspace = true
tui-textarea.workspace = true
strip-ansi-escapes.workspace = true
serde_json.workspace = true
serde.workspace = true
uuid.workspace = true
unicode-width.workspace = true
unicode-segmentation.workspace = true
arboard.workspace = true
kommand0-core.workspace = true

[dev-dependencies]
portable-pty = "0.9.0"
vt100 = "0.15"
tempfile.workspace = true
