#!/bin/sh
# Render the Homebrew formula for a kommand0 release to stdout. Used by CI (the
# `update-homebrew` release job) and runnable by hand for a local check.
#
#   scripts/render-homebrew-formula.sh <version> <macos_sha256> <linux_sha256>
#
# <version> may be "0.1.5" or "v0.1.5".
set -eu

[ $# -eq 3 ] || {
	echo "usage: $0 <version> <macos_sha256> <linux_sha256>" >&2
	exit 1
}

version=${1#v} # strip a leading v if present
macos_sha=$2
linux_sha=$3

# Note: the macOS download is a universal binary, so on_arm/on_intel point at the
# same archive — Homebrew requires url/sha256 to live in an arch block, not
# directly in on_macos.
cat <<EOF
# typed: true
# frozen_string_literal: true

# Homebrew formula for kommand0 — auto-generated by
# scripts/render-homebrew-formula.sh on each release. Edits here are overwritten.
class Kommand0 < Formula
  desc "Keyboard-first local orchestrator for parallel Claude Code sessions"
  homepage "https://github.com/cstuncsik/kommand0"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cstuncsik/kommand0/releases/download/v$version/kommand0-v$version-macos-universal.tar.gz"
      sha256 "$macos_sha"
    end
    on_intel do
      url "https://github.com/cstuncsik/kommand0/releases/download/v$version/kommand0-v$version-macos-universal.tar.gz"
      sha256 "$macos_sha"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cstuncsik/kommand0/releases/download/v$version/kommand0-v$version-linux-x86_64.tar.gz"
      sha256 "$linux_sha"
    end
  end

  def install
    bin.install "kommand0", "kmd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kommand0 --version")
    assert_match version.to_s, shell_output("#{bin}/kmd --version")
  end
end
EOF
